version: '3.4'

services:
  imdsapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${USERPROFILE}/.Azure:C:\Users\ContainerUser\.Azure:rw

networks:
  default:
    external:
      name: nat
